"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _storybookInfo = require("../../../../../.storybook/style/storybook-info.styles");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var info = _react.default.createElement("div", null, _react.default.createElement("p", null, "Radio Button Component"), _react.default.createElement("p", null, "A radio button widget. Selects one option from a longer list. Designed to be used with the RadioButtonGroup component, but can be used separately if you choose to write your own grouping (this is how the component was used pre-DLS)."), _react.default.createElement(_storybookInfo.StoryHeader, null, "Implementation"), _react.default.createElement("p", null, "Import the components:"), _react.default.createElement(_storybookInfo.StoryCodeBlock, null, 'import { RadioButton, RadioButtonGroup } from "carbon-react/lib/components/radio-button"'), _react.default.createElement("p", null, "To render the button group:"), _react.default.createElement(_storybookInfo.StoryCodeBlock, null, '<RadioButtonGroup groupName="frequency" legend="Please select a frequency from the options below">', '  <RadioButton value="weekly" label="Weekly"/>', '  <RadioButton value="monthly" label="Monthly"/>', '  <RadioButton value="annually" label="Annually"/>', '<RadioButtonGroup/>'), _react.default.createElement("p", null, "The ", _react.default.createElement(_storybookInfo.StoryCode, null, "groupName"), " prop supplied to the ", _react.default.createElement(_storybookInfo.StoryCode, null, "RadioButtonGroup"), " component is used to set the ", _react.default.createElement(_storybookInfo.StoryCode, null, "name"), " prop for each child element. If using the buttons separately, this can be set manually on each button."), _react.default.createElement("p", null, "The ", _react.default.createElement(_storybookInfo.StoryCode, null, "id"), " prop for each button can be set manually. If none is set, a random GUID will be used instead."), _react.default.createElement("p", null, "For additional properties specific to this component, see propTypes."), _react.default.createElement(_storybookInfo.StoryHeader, null, "Keyboard Support/Accessbility:"), _react.default.createElement("table", {
  className: "info-table"
}, _react.default.createElement("thead", null, _react.default.createElement("tr", null, _react.default.createElement("td", null, "Key"), _react.default.createElement("td", null, "Function"))), _react.default.createElement("tbody", null, _react.default.createElement("tr", null, _react.default.createElement("td", null, "Tab"), _react.default.createElement("td", null, _react.default.createElement("ul", null, _react.default.createElement("li", null, "Moves keyboard focus to the checked radio button in a radiogroup."), _react.default.createElement("li", null, "If no radio button is checked, focus moves to the first radio button in the group."), _react.default.createElement("li", null, "Further tab moves focus out of the radio group to the next component on the page.")))), _react.default.createElement("tr", null, _react.default.createElement("td", null, "Space"), _react.default.createElement("td", null, _react.default.createElement("ul", null, _react.default.createElement("li", null, "If the radio button with focus is unchecked, its state will be changed to checked.")))), _react.default.createElement("tr", null, _react.default.createElement("td", null, "Down/Right arrow"), _react.default.createElement("td", null, _react.default.createElement("ul", null, _react.default.createElement("li", null, "Moves focus to next radio button in the group."), _react.default.createElement("li", null, "If focus is on the last radio button in the group, move focus to the first radio button.")))), _react.default.createElement("tr", null, _react.default.createElement("td", null, "Up/Left arrow"), _react.default.createElement("td", null, _react.default.createElement("ul", null, _react.default.createElement("li", null, "Moves focus to previous radio button in the group."), _react.default.createElement("li", null, "If focus is on the first radio button in the group, move focus to the last radio button.")))))));

var _default = info;
exports.default = _default;